### ISSUE TITLE
Icons for oscal-compass

### ISSUE THREAD

**Issue by ancatri** [oscal-compass/community#10]
We work on icons with IBM Distinguished Designer Mike Abbink

**Comment by ancatri** [comment]
@jpower432  Jenn, do you have access to Adobe Illustrator ?

**Comment by mjabbink** [comment]
These are the potential lock-up scale relationships.

<img width="1855" alt="Screenshot 2024-06-04 at 12 07 19 PM" src="https://github.com/oscal-compass/community/assets/32881239/841c4fa6-92de-4eec-8701-e5b1a872eb20">

**Comment by mjabbink** [comment]
@ancatri — Plus these. Still working on getting you the SVG and PNG assets for all.

<img width="1061" alt="Screenshot 2024-06-04 at 2 26 01 PM" src="https://github.com/oscal-compass/community/assets/32881239/67a30c36-1a98-4ce2-93f1-4ece0da6d24f">

**Comment by mjabbink** [comment]
Here are some starters. INcludes a few PNG, SVG and EPS files
[oscal-compass-icons.zip](https://github.com/user-attachments/files/15569642/oscal-compass-icons.zip)

**Comment by mjabbink** [comment]
[oscal-compass-icons.zip](https://github.com/user-attachments/files/15570004/oscal-compass-icons.zip)

**Comment by ancatri** [comment]
@mjabbink Thank you Mike, they look outstanding! This is a great help for us on the non-designers side of the world. Thanks again!

@jpower432 @jay Please check if we have all we need to update our git repos with these AWSOME logos.

**Comment by ancatri** [comment]
left is C2P
middle T is well Trestle
right is Agile Auth

**Comment by mjabbink** [comment]
I provided each just as the icon which should work for the git repos. Let me know otherwise

**Comment by mjabbink** [comment]
I wanted to confirm If this is an IBM-branded initiative or not. If IBM, I want to ensure we do not use these as “logos” and think of them as icons or favicons. The brand team is in the process of removing “logos” from Cloud and Security to focus on one master brand with the 8-bar as the ONE logo.

If this is not an IBM-branded initiative and a larger community of contributors, stakeholders, etc., then my previous statement does not apply.

**Comment by mjabbink** [comment]
@ancatri I updated the folders above to just have the icons so there is no lockup so it looks like a logo with type.
