### ISSUE TITLE
Add Google Group to Community Communication

### ISSUE THREAD

**Issue by jflowers** [oscal-compass/community#23]
We need an email distribution list. I create one on Google Groups: https://groups.google.com/g/oscal-compass

**Comment by jflowers** [comment]
BTW who should be added as managers of this Google Group?

**Comment by jpower432** [comment]
Since Vikas and I are the community repo mantainers, I think it would make sense for us to be added. Thoughts @vikas-agarwal76?

**Comment by vikas-agarwal76** [comment]
> Since Vikas and I are the community repo mantainers, I think it would make sense for us to be added. Thoughts @vikas-agarwal76?

Sure.
