### ISSUE TITLE
Add Shared Calendar to README

### ISSUE THREAD

**Issue by jflowers** [oscal-compass/community#24]
Add shared Calendar to make it easier for people to attend our meetings. When people add this shared calendar to their own, they will get reminders, updates to events, and see new events.

**Comment by jflowers** [comment]
BTW who should be added as managers of this shared calendar?

**Comment by jpower432** [comment]
@jflowers Please add @vikas-agarwal76 and I as managers.

**Comment by jpower432** [comment]
Closed through #27
