### ISSUE TITLE
CODE_OF_CONDUCT.md Report Email

### ISSUE THREAD

**Issue by jflowers** [oscal-compass/community#25]
We should create and use a Google Group email address for reporting issues and enforcement in the CODE_OF_CONDUCT.md

**Comment by jflowers** [comment]
What should the name of the group be? Maybe oscal-compass-oversight?
If so, then we can have everyone on the Oversight Committee in that Google Group.

**Comment by vikas-agarwal76** [comment]
Seems fine.

**Comment by jflowers** [comment]
The group is created, and I have added Jenn and Vikas. I need to get the others email addresses so I can add them to the group.

**Comment by jpower432** [comment]
@jflowers Can this issue be closed or are you using it to track the creation/update of the mailing list?

**Comment by jflowers** [comment]
nope, it can be closed as it was merged

**Comment by jflowers** [comment]
done
