### ISSUE TITLE
[VOTE] Governance Review and Approval

### ISSUE THREAD

**Issue by jpower432** [oscal-compass/community#31]
## Overview

Initial governance documentation is in place and an bootstrap [Oversight Committee](https://github.com/oscal-compass/community/blob/main/MAINTAINERS.md) has been identified. 

## Action Requested

Review the following documentation:
[GOVERNANCE.md](https://github.com/oscal-compass/community/blob/main/GOVERNANCE.md)
[MEMBERSHIP.md](https://github.com/oscal-compass/community/blob/main/MEMBERSHIP.md)

Express approval and acknowledgement of the processes in place. Other community members may express approval and make suggestions, but to close this issue we need a supermajority vote of the Oversight Committee

Any major concerns that need to be addressed prior to approval should be recorded and worked through an issue.

### How to express approval

+1 in a comment or thumbs-up emoji on the description

### Deadline

**EDITED**: The deadline for feedback is July 12th.

## Intended Outcomes

The following should be submitted as separate, follow-on issues:

- Nominate/Choose an Oversight Committee chair #34
- Collaborate on Oversight Committee succession procedures
- Address any non-critical gaps in the governance documents

## CNCF OnBoarding Task

Start working on [written, open governance](https://contribute.cncf.io/maintainers/governance/).

**Comment by jflowers** [comment]
+1

**Comment by ancatri** [comment]
@jpower432 Jenn, I discussed with Jay to follow the typical CNCF chair structure of 3 ppl to cover vacations, absences, ties.

**Comment by jpower432** [comment]
@ancatri I am in favor of the idea of co-chairs. Given that the Oversight Committee only has 6 members, I think it might make more sense to have two chairs (a chair and a vice chair similar to the CNCF TOC structure). What do you think?

**Comment by jpower432** [comment]
Hey folks - I want to establish some timelines around the feedback and voting period since we have a mix of both. Is July 12th a reasonable end date for feedback so we can alter the policy for re-review?

**Comment by ancatri** [comment]
@jpower432 We can have 2 chairs for now and revisit as we grow the committee base. Makes sense
I would like to nominate @mangiree gadgil as a chair together with @jflowers - I hope to find the right issue/PR :)

For the deadline, any date close to July 16th when we have the community call would work. July 12 or July 15. Thanks!

**Comment by jpower432** [comment]
Thanks @ancatri. I will add the date details to the description.

**Comment by yuji-watanabe-jp** [comment]
+1

**Comment by jpower432** [comment]
This issue will be reviewed for closure at the next Oversight Committee meeting occurring July 30.

**Comment by degenaro** [comment]
+1

**Comment by jpower432** [comment]
Closing this as we have approval by 2/3 of the Oversight Committee.
