### ISSUE TITLE
Nominate Oversight Committee chairs

### ISSUE THREAD

**Issue by jpower432** [oscal-compass/community#34]
## Overview

The primary role of the Oversight Committee chairs is to facilitate operations and governance of the Oversight Committee.

Chairs responsibilities include:

- Setting the agenda for meetings
- Scheduling and facilitating Oversight Committee meetings
- Extending discussion via asynchronous communication to be inclusive of members who cannot attend a specific meeting time
- Facilitating the creation and execution of Oversight Committee activities

## Eligibility 
Those who are eligible to be nominated are current Oversight Committee members listed [here](https://github.com/oscal-compass/community/blob/main/MAINTAINERS.md#oversight-committee).

## Nominations

Nominations will be open until July 5th. 

Eligible people can nominate themselves.
If you plan to nominate somebody else please ensure that they accept the nomination.

### How to nominate

Please include a short nomination **comment on this issue** with the following details:

- Name of the nominee
- Motivation for the role
- Commitment on how much time you/they can dedicate to the role

### Notes

This issue is preceding a formally defined Oversight Committee selection process. Per the governance documentation, this will be defined and finalized by the bootstrap Oversight Committee.

Based on community feedback, this can serve as a example or template for the formally defined process.

Related to #31

**Comment by vikas-agarwal76** [comment]
@jpower432 Where the votes have to be captured? as part of the comments to this issue?

**Comment by jpower432** [comment]
@vikas-agarwal76 Yes. To nominate someone please add a comment with the following information:

- Name of the nominee
- Motivation for the role
- Commitment on how much time you/they can dedicate to the role

**Comment by jflowers** [comment]
I have a very particular set of skills. Skills I have acquired over a very long career. Skills in creating and cultivating open source communities. I enjoy facilitating, coaching, and growing open source communities. I am lucky enough that my day job not only provides me the opportunity to take on a community commitment like this, it incentivizes me to. I can dedicate 4 or more hours a week to this role.

—[Liam Neeson](https://www.imdb.com/name/nm0000553/?ref_=tt_ov_st),[Taken](https://www.imdb.com/title/tt0936501/)

**Comment by ancatri** [comment]
Hi, as discussed with Jay, I suggested to have 3 Oversight Committee Chairs following the current practices in TAG and WG Chairs.

**Comment by jpower432** [comment]
> Hi, as discussed with Jay, I suggested to have 3 Oversight Committee Chairs following the current practices in TAG and WG Chairs.

@ancatri Thanks for adding this comment. Can you please take a look at the pull request to collaborate on this change I have open (#36) and my response on #31. Once agreed, we can add additional clarity on the ticket and extend the nomination period if need be.

**Comment by ancatri** [comment]
@jpower432 I would like to nominate @mrgadgil as a chair together with @jflowers - I hope to find the right issue/PR :)

**Comment by jpower432** [comment]
You have the right issue. Thanks @ancatri!

**Comment by ancatri** [comment]
@mrgadgil Nomination issue #34 - FYI

**Comment by jpower432** [comment]
Based on the results of this issue and #37, @jflowers and @mrgadgil will be co-chairs. I will submit a pull request updating the `maintainers` file for review.
