### ISSUE TITLE
Add Introductory Recording 

### ISSUE THREAD

**Issue by ancatri** [oscal-compass/community#41]
Make it available / referenced from the Org/community page
we can reference it from the Trestle tutorial as well
Jenn and I have both downloaded it inc case it desaprears w Webex

**Comment by jpower432** [comment]
@ancatri Below is a high-level plan

- Make the video available in the OSCAL Compass YouTube channel
- Embed video in community `README.md`
- Add a sub-folder for presentation materials with a `README.md` with instructions on how to adapt and reuse the material for the community
