### ISSUE TITLE
Review all websites for compliance with website guidelines

### ISSUE THREAD

**Issue by jpower432** [oscal-compass/community#45]
On-boarding tasks pertaining to the website

> Note: This covers two checklist items

- [x] Ensure LF footer is on websites and guidelines are followed. The guidelines are located here - https://github.com/cncf/foundation/blob/main/website-guidelines.md
- [x]  Transfer website analytics to [projects@cncf.io](mailto:projects@cncf.io)

**Comment by degenaro** [comment]
The following PRs for OSCAL Compass repos have been created to address this issue:

1. https://github.com/oscal-compass/community/pull/76
2. https://github.com/oscal-compass/compliance-trestle/pull/1678
3. https://github.com/oscal-compass/compliance-trestle-agile-authoring/pull/10
4. https://github.com/oscal-compass/compliance-to-policy/pull/30
5. https://github.com/oscal-compass/compliance-trestle-demos/pull/50

**Comment by degenaro** [comment]
Note: The websites comprising the PRs for conformance with website guidelines (above) correspond to those specified in the CNCF landscape https://github.com/cncf/landscape/pull/4003 (or so is my claim).
