### ISSUE TITLE
Move oscal-compass organization to CNCF organization

### ISSUE THREAD

**Issue by AleJo2995** [oscal-compass/community#56]
OSCAL compass has been recently accepted to take part of the CNCF sandbox projects. As part of the move, we need to move the projects under oscal-compass umbrella to CNCF org.

Part of the tasks list to complete for the move are:

- [ ] Create a banner announcing the move
- [ ] Communicate the move within the community

**Comment by jpower432** [comment]
@AleJo2995 This has been completed and announced in Slack. No URL changes occurred.

**Comment by jpower432** [comment]
Closed by #57
