### ISSUE TITLE
Add project to CNCF landscape

### ISSUE THREAD

**Issue by jpower432** [oscal-compass/community#66]
## Onboarding item
- Submit a [pull request](https://github.com/cncf/landscape/pulls) to add your project as a Sandbox project to the [Cloud Native Landscape](https://landscape.cncf.io/) by updating [landscape.yml](https://github.com/cncf/landscape/blob/master/landscape.yml) following these [instructions](https://github.com/cncf/landscape2/blob/main/docs/config/data.yml).

**Comment by degenaro** [comment]
See draft PR here: https://github.com/cncf/landscape/pull/4003

See mock-up result here: https://landscape.cncf.io/?overlay-data=https%3A%2F%2Fraw.githubusercontent.com%2Fdegenaro%2Fcncf.landscape%2Fmaster%2Flandscape.yml&overlay-logos=https%3A%2F%2Fraw.githubusercontent.com%2Fdegenaro%2Fcncf.landscape%2Fmaster%2Fhosted_logos

**Comment by jpower432** [comment]
@degenaro Some initial feedback which I can also add the the PR:

`landscape.yml`

- I suggest we only list repos listed as in scope of the CNCF application by making `compliance-trestle` the repo URL and add C2P and AgileAuthoring under `additional_repos`.
- The GitHub Discussions should be updated to https://github.com/oscal-compass/community/discussions
- If we could get `https://github.com/oscal-compass/oscal-compass.github.io` populated I think `https://oscal-compass.github.io/` could be the homepage URL, but the community repo makes sense.
- We should add our Google group under `extra.mailing_list_url`

**Logo**

- The image looks a bit distorted and we could probably get away with a fully transparent background in this context

**Comment by degenaro** [comment]
Your points are well taken. Thx!

repos list - Let's discuss amongst all and come to a consensus. My claim is
that these are all directly related to the objective of the sandbox, and
are therefore bone fide additional repos. I may be alone in this view...or
not.
discussions - done
homepage - community for now, we can submit a PR when ready to switch to
https://oscal-compass.github.io/
fixed: extra.mailing_list_url = https://groups.google.com/g/oscal-compass
logo - this is both temporary and reflective of my poor artistic skills;
please feel free to provide an improved version once Anca gets the approved
artwork. Note that the name must be incorporated with the logo.

**Comment by degenaro** [comment]
logo is now fixed, using artwork from Abbink.

**Comment by degenaro** [comment]
https://github.com/cncf/landscape/pull/4003 merged into master.
